"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-j6t&a^n4m3kqw$+z6_xgxj3p_-sovq$ko+j8##zo2sonx-n()i'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rms',  
    'rest_framework',    
    'debug_toolbar',
    'django_filters',
    'rest_framework.authtoken',
    'drf_spectacular',
    'users',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "debug_toolbar.middleware.DebugToolbarMiddleware",
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }



# Postgres Integration
DATABASES = {
    'default' : {
        'ENGINE' : 'django.db.backends.postgresql',     # Path of 'postgresql' package
        'NAME'  : 'rms2',                               # Name of your database
        'USER' : 'postgres',                            # Username tha you have set
        'PASSWORD' : '123',                             # Password that you have set
        'HOST'  : 'localhost',                          # Host name. 'localhost' in this case
        'PORT'  : '5432'                                # Port. '5432' by default
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'



# INTERNAL IPS for debug toolbar
INTERNAL_IPS = [
    # ...
    "127.0.0.1",
    # ...
]



REST_FRAMEWORK = {
    
    # # Default pagination:
    # 'DEFAULT_PAGINATION_CLASS' : 'rest_framework.pagination.LimitOffsetPagination',   # pagination class takes single string
    # 'PAGE_SIZE' : 10, 
    
    
    # # Default django filters:
    # 'DEFAULT_FILTER_BACKENDS' : [
    #     'rest_framework.filters.SearchFilter', 
    #     'django_filters.rest_framework.DjangoFilterBackend', 
    #     'rest_framework.filters.OrderingFilter'
    #     ],                                                                     # filter backends must be a list/tuple, that's why '[ ]' is used here
    
    
    # Default authentication:
    'DEFAULT_AUTHENTICATION_CLASSES' : ['rest_framework.authentication.TokenAuthentication'],
    
    # # Default permission:
    # 'DEFAULT_PERMISSION_CLASSES' : ['rest_framework.permissions.IsAuthenticated'],
    
    
    # API documentation: 
    'DEFAULT_SCHEMA_CLASS' : 'drf_spectacular.openapi.AutoSchema', 

}



SPECTACULAR_SETTINGS = {
    'TITLE': 'Restaurant Management System',
    'DESCRIPTION': 'This is restaurant management system.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    # OTHER SETTINGS
}



AUTH_USER_MODEL = 'users.User'



# Email Setup (smtp) 
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_PORT = 587
EMAIL_USE_TLS = True   # USE_TLS : says, do you want to use TLS encryption while sending email(True/False)
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'nadafjilani182@gmail.com'
EMAIL_HOST_PASSWORD = 'jspfkrwtcuvjucfs' 