# Generated by Django 6.0.5 on 2026-06-15 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0002_alter_table_available_alter_table_table_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='food',
        ),
    ]
