# Generated by Django 6.0.5 on 2026-06-17 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0004_alter_food_category_alter_order_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
