# Generated by Django 6.0.5 on 2026-06-17 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0005_alter_order_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
