# Generated by Django 6.0.5 on 2026-06-19 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0006_alter_order_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.FloatField(null=True),
        ),
    ]
